branch-defaults:
  master:
    environment: prod-env
    group_suffix: null
deploy:
  artifact: target/urchin-release-mgt.zip
global:
  application_name: GreenCityReleaseMgt
  branch: null
  default_ec2_keyname: greencityreleasemgtkeys
  default_platform: Docker 18.06.1-ce
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
