server:
  port: 8080
  servlet.context-path: "/"
management:
  endpoints.web.exposure.include: "*"
spring:
  security.user:
    name: "admin"
    password: "$2a$10$SRSz7BSfnjvUnX7/BJyLSufHJOS5z6mDvo4lzeQkVUdYqGYtEx2UG"
  datasource:
    url: "jdbc:h2:tcp://localhost/~/urchinReleaseMgtDB;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate.ddl-auto: "update"
    show-sql: false
    open-in-view: false
actuator:
  password: "$2a$10$LP.C2c/pkgWQE2Z5x9JNNejYbh1lJ81au58xoUZa5ZnWh/4ROITfu"
issue:
  page-size: 10
  chart-days: 15
binary:
  base-url: "https://s3.eu-west-3.amazonaws.com/urchinreleasemgt/"
  version-pattern: "(\\d+[.]\\d+[.]\\d+)"
  chart-days: 15
