spring:
  datasource:
    url: "jdbc:h2:tcp://localhost:9191//home/greg/Project/urchin/urchinReleaseMgt/database/urchinReleaseMgtDB;DB_CLOSE_ON_EXIT=FALSE"
binary:
  aws-bucket-name: "greencity-releasemgt"
