server:
  port: 8080
  servlet.context-path: "/"
management.endpoints.web.exposure.include: "*"
spring:
  security.user:
    name: "admin"
    password: "$2a$10$SRSz7BSfnjvUnX7/BJyLSufHJOS5z6mDvo4lzeQkVUdYqGYtEx2UG"
  datasource:
    url: "jdbc:h2:~/urchinReleaseMgtDB;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate.ddl-auto: "update"
    show-sql: false
security:
  password-strength: 10
  api-user: "api"
  api-password: "$2a$10$PC.ynuA8ojXtfkSnXFZVU.8ORkVcB6NmI3gOPsyAKWXJtZlGLJlKu"
issue:
  base-folder: "/home/greg/_issue/"
  page-size: 10
  chart-days: 15
binary:
  base-folder: "/home/greg/_binary/"
  version-pattern: "(\\d[.]\\d[.]\\d)"
  chart-days: 15
